name: Create Release Version

on:
    push:
    workflow_dispatch:
    schedule:
        - cron: 0 16 * * 0

jobs:
    release:
        uses: ./.github/workflows/create_release_version_reuse.yaml
        with:
            branch_pattern: version/*
        secrets: inherit
