name: Release

on:
  workflow_dispatch:
    inputs:
      type:
        required: true
        description: What type of release to make
        type: string

jobs:
  release:
    uses: ./.github/workflows/release_reuse.yaml
    with:
      version: 1.21
      type: ${{ inputs.type }}
    secrets: inherit
